# spring.application.name=appointmentservice
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.h2.console.enabled=true

#H2
# spring.application.name=appointmentservice
# #spring.datasource.url=jdbc:h2:mem:userservice;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.url=jdbc:h2:mem:file:./data/userservice;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# spring.datasource.username=sa
# spring.datasource.password=abc
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

##AWS RDS
spring.application.name=appointmentservice
spring.datasource.url=jdbc:postgresql://hospital-db.c3e0qs04qmz2.ap-southeast-1.rds.amazonaws.com:5432/appointmentservice
#spring.datasource.url=jdbc:postgresql://ec2-13-229-204-92.ap-southeast-1.compute.amazonaws.com:5432/userservice
spring.datasource.username=postgres
spring.datasource.password=rootroot
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
